version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    groups:
      actions-minor:
        update-types:
          - 'minor'
          - 'patch'
    labels:
      - "patch"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    groups:
      npm-development:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      npm-production:
        dependency-type: 'production'
        update-types:
          - 'patch'
    labels:
      - "patch"
      - "dependencies"
