version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "patch"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "⬆️ "
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "patch"
      - "dependencies"
