name: 'Semver Tag Action'
description: 'Tag a semantic version'
inputs:
  tag:
    description: 'The specific value to tag by - any Semver accepted value allowed'
    required: false
  github_token:
    description: 'Github API token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
