name: 'Semver Tag Action'
description: 'Create the next semantic version and tag it'
inputs:
  increment:
    description: 'The amount to increment the last tag by (ignored if `tag` is specified - any Semver accepted value allowed'
    required: false
  tag:
    description: 'The specific value to tag by - any Semver accepted value allowed'
    required: false
  github_token:
    description: 'Github API token'
    required: true
  dry_run:
    description: 'Specify to not create resulting tag against repository'
    required: false
  default_use_head_tag:
    description: 'Use the highest semver tag value on repository'
    required: false
outputs:
  version:
    description: 'The new SemVer tag'
runs:
  using: 'node16'
  main: 'dist/index.js'
