name: 'Semver Tag Action'
description: 'Create the next semantic version and tag it'
inputs:
  increment:
    description: 'The amount to increment the tag by - any Semver accepted value allowed'
    required: true
  github_token:
    description: 'Github API token'
    required: true
  dry_run:
    description: 'Specify to not create resulting tag against repository'
    required: false
outputs:
  version:
    description: 'The new SemVer tag based on the existing tag + increment'
runs:
  using: 'node16'
  main: 'dist/index.js'
