name: "Unit Tests"
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  pr-units:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run the tests
        run: npm run test
